name: Build FFmpegKit AAR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android-aar:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk  # 声明 SDK 根目录

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          link-to-sdk: true

      - name: Export NDK path
        run: echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git build-essential yasm pkg-config

      - name: Build FFmpegKit AAR
        run: |
          cd ffmpeg-kit-myvideo
          bash android.sh \
            --ffmpeg-extra-config="$EXTRA_CFG" \
            --disable-libraries \
            --enable-libraries=""

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-myvideo-aar
          path: ffmpeg-kit-myvideo/prebuilt/bundle-android-aar/*.aar