name: Build FFmpegKit AAR

on:
  workflow_dispatch:     # 手动触发
  push:
    branches: [ main ]

jobs:
  build-android-aar:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-ndk@v2
        with:
          ndk-version: '27.0.12077973'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git build-essential yasm pkg-config

      - name: Build FFmpegKit AAR
        run: |
          export ANDROID_NDK_ROOT="${{ steps.setup-ndk.outputs.ndk-path }}"
          cd ffmpeg-kit-myvideo
          bash android.sh --ffmpeg-extra-config="$EXTRA_CFG" \
                          --disable-libraries --enable-libraries=""

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-kit-myvideo-aar
          path: ffmpeg-kit-myvideo/prebuilt/bundle-android-aar/*.aar
